#ifndef OCTASPIRE_LIGHTBOARD_INPUT_H
#define OCTASPIRE_LIGHTBOARD_INPUT_H

typedef enum octaspire_lightboard_input_t
{
    OCTASPIRE_LIGHTBOARD_INPUT_NONE,
    OCTASPIRE_LIGHTBOARD_INPUT_UP,
    OCTASPIRE_LIGHTBOARD_INPUT_DOWN,
    OCTASPIRE_LIGHTBOARD_INPUT_LEFT,
    OCTASPIRE_LIGHTBOARD_INPUT_RIGHT,
    OCTASPIRE_LIGHTBOARD_INPUT_RESTART,
    OCTASPIRE_LIGHTBOARD_INPUT_ACTION_1
}
octaspire_lightboard_input_t;

#endif

